#!/usr/bin/env bash
# Container entrypoint: render the config from the environment, pull the newest agent,
# then hand off to it as pid 1.
#
# Configuration is entirely by environment — the image ships no config.ini, so a token
# can never be baked into a layer. Required:
#
#   ZIDANE_BACKEND_WSS_URL   wss://zidane.example.com:17001/ws/agent
#   ZIDANE_BACKEND_API_KEY   registration token from Settings -> Agent registration tokens
#
# Optional: ZIDANE_AGENT_NAME (default: the container hostname), ZIDANE_AGENT_CAPACITY,
# ZIDANE_AGENT_LABELS, ZIDANE_LOGGING_LEVEL, ZIDANE_UPGRADE_ON_START=0 to pin the version
# baked into the image.
set -euo pipefail

INSTALL_ROOT="${ZIDANE_INSTALL_ROOT:-/opt/mangosteen/zidane-agent}"
CONFIG="$INSTALL_ROOT/conf/config.ini"

info() { echo "==> $*"; }
die()  { echo "error: $*" >&2; exit 1; }

[[ -n "${ZIDANE_BACKEND_WSS_URL:-}" ]] \
  || die "ZIDANE_BACKEND_WSS_URL is required (e.g. wss://host:17001/ws/agent)"
[[ -n "${ZIDANE_BACKEND_API_KEY:-}" ]] \
  || die "ZIDANE_BACKEND_API_KEY is required; create one under Agent registration tokens"

# --- 1. upgrade to the newest published release ----------------------------
# Deliberately non-fatal. A container that cannot reach GitHub — air-gapped, rate-limited,
# GitHub down — must still come up on the version baked into the image rather than
# crash-loop. The agent declines the backend's in-band upgrade while containerised
# (UPGRADE_SKIPPED), so a restart is how a container moves version; this is that path.
if [[ "${ZIDANE_UPGRADE_ON_START:-1}" != "0" ]]; then
  info "checking for a newer agent release"
  if ! bash /usr/local/bin/upgrade.sh --install-root "$INSTALL_ROOT" --user zidane --no-restart; then
    echo "warning: upgrade check failed; continuing on the installed version" >&2
  fi
fi

# --- 2. render the config from the environment -----------------------------
# Rewritten every start: the environment is the source of truth for a container, and a
# config left over in a bind-mounted conf/ would silently outrank a changed -e flag.
#
# One consequence worth knowing: a backend SET_CONFIG push rewrites this file at run time
# (capacity, labels), and that survives until the next restart, when the environment wins
# again. Set only what you intend to pin.
mkdir -p "$(dirname "$CONFIG")" "$INSTALL_ROOT/state" "$INSTALL_ROOT/logs" \
         "${ZIDANE_AGENT_WORKDIR_ROOT:-/opt/mangosteen/zidane-workspace}"

# `docker run --name` names the *container*, not its hostname, so without this the agent
# shows up in the console as the random container id — and because the backend reuses a
# record only when hostname *and* name match, every recreated container leaves a ghost.
if [[ -z "${ZIDANE_AGENT_NAME:-}" ]]; then
  echo "note: no ZIDANE_AGENT_NAME set; registering as the container hostname" \
       "'$(hostname)'." >&2
  echo "      For a stable identity across 'docker rm', pass both:" >&2
  echo "        -e ZIDANE_AGENT_NAME=build-01 --hostname build-01" >&2
fi

cat > "$CONFIG" <<EOF
# Generated by docker-entrypoint.sh on every container start. Edit the container's
# environment, not this file.
[agent]
name = ${ZIDANE_AGENT_NAME:-$(hostname)}
capacity = ${ZIDANE_AGENT_CAPACITY:-4}
labels = ${ZIDANE_AGENT_LABELS:-os=linux}
auto_upgrade = false
upgrade_channel = ${ZIDANE_AGENT_UPGRADE_CHANNEL:-stable}
state_dir = ${ZIDANE_AGENT_STATE_DIR:-$INSTALL_ROOT/state}
workdir_root = ${ZIDANE_AGENT_WORKDIR_ROOT:-/opt/mangosteen/zidane-workspace}
install_root = $INSTALL_ROOT

[backend]
wss_url = ${ZIDANE_BACKEND_WSS_URL}
api_key = ${ZIDANE_BACKEND_API_KEY}

[logging]
file = ${ZIDANE_LOGGING_FILE:-$INSTALL_ROOT/logs/agent.log}
level = ${ZIDANE_LOGGING_LEVEL:-INFO}
max_mb = ${ZIDANE_LOGGING_MAX_MB:-50}
file_count = ${ZIDANE_LOGGING_FILE_COUNT:-5}
EOF
chmod 600 "$CONFIG"

# The env vars that config.py reads outrank the file, and the file above already holds
# their values. Clearing the token means it is not in the environment of every task the
# agent spawns — `env` in a build script would otherwise print it.
unset ZIDANE_BACKEND_API_KEY

VERSION_DIR="$(readlink -f "$INSTALL_ROOT/current")"
info "starting zidane-agent from $(basename "$VERSION_DIR")"

# exec: the agent becomes pid 1 and gets SIGTERM straight from `docker stop`, so it can
# report in-flight results before the runtime kills it.
cd "$VERSION_DIR"
exec "$VERSION_DIR/.venv/bin/python" -m app.main --config "$CONFIG" "$@"
