#!/usr/bin/env bash
#
# Cut a zidane-agent release: bump the version, commit, tag, build the tarball, publish a
# GitHub release with the tarball + SHA256SUMS attached, and print the three values the
# backend needs for one-click self-upgrade.
#
# Usage:
#   scripts/release.sh 0.2.0      # bump to 0.2.0, then release it
#   scripts/release.sh            # release the current version as-is
#
# Env overrides:
#   REPO    GitHub repo (default: mangosteen-lab/zidane-agent)
#   NOTES   release notes (default: auto-generated by gh)
#
# Prereqs: gh CLI logged in, a clean working tree, push access.
#
# Two things this guards against, both of which produce a release that looks fine and
# breaks on the machine that installs it:
#
#   1. The version lives in *two* files — pyproject.toml (packaging) and app/client.py
#      (what the agent reports over the wire, and what the backend compares against to
#      decide whether an upgrade is needed). They must agree, or the fleet upgrades in a
#      loop: the backend keeps offering a version the agent never claims to have reached.
#   2. The tarball is built with `git archive HEAD`, so an uncommitted bump would ship the
#      old version under the new filename. The build is verified after the fact.
set -euo pipefail

cd "$(dirname "$0")/.."

REPO="${REPO:-mangosteen-lab/zidane-agent}"

pyproject_version() {
  python3 -c "import tomllib;print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])"
}
client_version() {
  python3 -c "import re,pathlib;print(re.search(r'AGENT_VERSION = \"([^\"]+)\"',pathlib.Path('app/client.py').read_text()).group(1))"
}

REQUESTED="${1:-}"; REQUESTED="${REQUESTED#v}"

# --- preflight -------------------------------------------------------------
command -v gh >/dev/null       || { echo "error: gh CLI not found"; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "error: not logged in — run: gh auth login"; exit 1; }
[ -z "$(git status --porcelain)" ] || { echo "error: working tree is not clean"; exit 1; }

# --- 1. bump both version sites, then commit -------------------------------
CURRENT="$(pyproject_version)"
if [ -n "$REQUESTED" ] && [ "$REQUESTED" != "$CURRENT" ]; then
  echo ">> Bumping $CURRENT -> $REQUESTED (pyproject.toml + app/client.py)"
  python3 - "$REQUESTED" <<'PY'
import pathlib, re, sys

version = sys.argv[1]
for path, pattern, replacement in (
    ("pyproject.toml", r'(?m)^version\s*=\s*".*"$', f'version = "{version}"'),
    ("app/client.py", r'(?m)^AGENT_VERSION = ".*"$', f'AGENT_VERSION = "{version}"'),
):
    file = pathlib.Path(path)
    text, count = re.subn(pattern, replacement, file.read_text(), count=1)
    if count != 1:
        sys.exit(f"could not find a version line to replace in {path}")
    file.write_text(text)
PY
  git commit -aqm "Release $REQUESTED"
fi

VERSION="$(pyproject_version)"
[ "$VERSION" = "$(client_version)" ] || {
  echo "error: pyproject.toml says $VERSION but app/client.py says $(client_version)."
  echo "       The agent reports the second one; a mismatch makes the fleet upgrade in a loop."
  exit 1
}

TAG="v$VERSION"
TARBALL="dist/zidane-agent-$VERSION.tar.gz"
echo ">> Releasing $REPO @ $TAG"

# --- 2. build, then verify the archive really carries this version ---------
make release-tarball >/dev/null
[ -f "$TARBALL" ] || { echo "error: expected $TARBALL after build"; exit 1; }
IN_TAR="$(tar xzOf "$TARBALL" pyproject.toml | sed -n 's/^version *= *"\(.*\)"/\1/p' | head -1)"
[ "$IN_TAR" = "$VERSION" ] || {
  echo "error: tarball holds version '$IN_TAR', expected '$VERSION' — was the bump committed?"
  exit 1
}
echo ">> Verified tarball version = $IN_TAR"

SHA256="$(python3 -c "import hashlib,sys;print(hashlib.sha256(open(sys.argv[1],'rb').read()).hexdigest())" "$TARBALL")"
( cd dist && printf '%s  %s\n' "$SHA256" "$(basename "$TARBALL")" > SHA256SUMS )

# --- 3. tag and push -------------------------------------------------------
git rev-parse -q --verify "refs/tags/$TAG" >/dev/null || git tag "$TAG"
git push origin HEAD
git push origin "$TAG"

# --- 4. publish ------------------------------------------------------------
if gh release view "$TAG" --repo "$REPO" >/dev/null 2>&1; then
  echo ">> Release $TAG exists; re-uploading assets"
  gh release upload "$TAG" "$TARBALL" dist/SHA256SUMS --repo "$REPO" --clobber
else
  gh release create "$TAG" "$TARBALL" dist/SHA256SUMS \
    --repo "$REPO" --title "zidane-agent $VERSION" \
    ${NOTES:+--notes "$NOTES"} ${NOTES:---generate-notes}
fi

URL="https://github.com/$REPO/releases/download/$TAG/$(basename "$TARBALL")"

cat <<EOF

Release published: https://github.com/$REPO/releases/tag/$TAG

Install on a machine:
  curl -fsSL https://raw.githubusercontent.com/$REPO/main/scripts/install.sh | sudo bash -s -- \\
    --url wss://<backend>:17001/ws/agent --token <YOUR_TOKEN>

Set these on the backend so the fleet can self-upgrade (then restart it):
  ZIDANE_AGENT_RELEASE_VERSION=$VERSION
  ZIDANE_AGENT_RELEASE_URL=$URL
  ZIDANE_AGENT_RELEASE_SHA256=$SHA256

The agent refuses an artifact whose digest does not match, so publishing the sha256 is
what makes that check real rather than decorative.
EOF
